### ISSUE TITLE
cabocha の feature について

### ISSUE THREAD

**Issue by ByeongseonPark** [okayu9/taset#1]
`01mkdata` の `01do.sh` によって実行される `seikei.py` では、
https://github.com/okayu9/taset/blob/3195629e0695bcafb2de7d2450eff858b74851ad/train/01mkdata/seikei.py#L64
のようにchabochaによる分析結果上で feature が25個であればデータの整形が行われると書かれていますが、私の環境でスクリプトに書かれたcabochaの実行コマンド `cabocha -O2 -d /usr/local/lib/mecab/dic/unidic` では、常にfeatureの数は17個でした。

- テスト環境
    - mecab : 0.996
    - unidic : 2.1.2
    - cabocha : 0.69

```cmd
$ echo '平常運転になりました' | cabocha -O2 -d /usr/local/lib/mecab/dic/unidic
> * 0 -1D
> 平常	名詞,普通名詞,一般,*,*,*,ヘイジョウ,平常,平常,ヘージョー,平常,ヘージョー,漢,*,*,*,*
> 運転	名詞,普通名詞,サ変可能,*,*,*,ウンテン,運転,運転,ウンテン,運転,ウンテン,漢,*,*,*,*
> に	助詞,格助詞,*,*,*,*,ニ,に,に,ニ,に,ニ,和,*,*,*,*
> * 1 -1D
> なり	動詞,非自立可能,*,*,五段-ラ行,連用形-一般,ナル,成る,なり,ナリ,なる,ナル,和,*,*,*,*
> まし	助動詞,*,*,*,助動詞-マス,連用形-一般,マス,ます,まし,マシ,ます,マス,和,*,*,*,*
> た	助動詞,*,*,*,助動詞-タ,終止形-一般,タ,た,た,タ,た,タ,和,*,*,*,*
> EOS
```

unidicの素性に関する定義ファイル `unidic/dicrc` の記述を見る限りでも feature は17個で、これ以上の feature をどうすれば表示できるのかわかりませんでした。

```
; List of features
; f[0]:  pos1
; f[1]:  pos2
; f[2]:  pos3
; f[3]:  pos4
; f[4]:  cType
; f[5]:  cForm
; f[6]:  lForm
; f[7]:  lemma
; f[8]:  orth
; f[9]:  pron
; f[10]: orthBase
; f[11]: pronBase
; f[12]: goshu
; f[13]: iType
; f[14]: iForm
; f[15]: fType
; f[16]: fForm
```

これは設定やバージョンの違いがあるのでしょうか？
もしそれ等が必要であれば教えてもらえないでしょうか。

**Comment by okayu9** [comment]
TASETにはアクセントが付与されたUniDicを使用する必要があります。
こちらから unidic-mecab_kana-accent-2.1.2_src.zip をダウンロードしてご使用ください。
https://unidic.ninjal.ac.jp/back_number

なお、私はTASETの作者ではなく、TASETを修正BSDライセンスに従い再配布しているものです。
そのため、TASETに関する質問等は https://sites.google.com/site/suzukimasayuki/accent にある連絡先にお願いします。

**Comment by ByeongseonPark** [comment]
コメントありがとうございます。
教えてくださった内容をもとにもう一度試させていただきます。
また、今後 TASET に関する質問先についても改めさせていただきます。
ご対応ありがとうございました。
